### ISSUE TITLE
It's hardcoded to 2017/12

### ISSUE THREAD

**Issue by umpirsky** [vitogit/vue-chess-guardian#1]
https://github.com/vitogit/vue-chess-guardian/blob/master/src/App.vue#L100

For me it does not find games.

Keep up the good work! :)

**Comment by vitogit** [comment]
Hi, yes I will add the option to select month and year. Because is the way that chess.com API works. You can´t bring all your games from 1 query. 

Also make the error message a little more clear , like how many games you have (the program needs at least 10)

**Comment by vitogit** [comment]
This commit https://github.com/vitogit/vue-chess-guardian/commit/a00bf8b4c4321b663e5a59b61e8dc46a707bc505 adds the month/year selector and resolves the hardcoded problem
